/** Plain-language names for what the audit log records; the raw code stays visible beside them. */
export const auditActions: Record<string, string> = {
  AREA_CREATED: "Área creada",
  ASSIGNMENT_CHANGED: "Asignación cambiada",
  CLARIFICATION_CLOSED: "Aclaración cerrada",
  CLARIFICATION_REQUESTED: "Aclaración solicitada",
  CLARIFICATION_RESPONDED: "Aclaración respondida",
  CONFLICT_MARKED: "Conflicto registrado",
  CONFLICT_RESOLVED: "Conflicto resuelto",
  EVIDENCE_ATTACHED: "Evidencia adjuntada",
  EVIDENCE_DOWNLOADED: "Evidencia descargada",
  EVIDENCE_STAGED: "Evidencia preparada",
  EXPORT_CREATED: "Exportación creada",
  INVITATION_CREATED: "Invitación creada",
  INVITATION_OPENED: "Invitación abierta",
  INVITATION_RENEWED: "Enlace de invitación renovado",
  INVITATION_REVOKED: "Invitación revocada",
  LOGIN: "Inicio de sesión",
  LOGOUT: "Cierre de sesión",
  PASSWORD_CHANGED: "Contraseña cambiada",
  PROJECT_CREATED: "Proyecto creado",
  PROJECT_IMPORTED: "Cuestionario importado",
  PROJECT_MEMBER_CHANGED: "Miembro del proyecto cambiado",
  QUESTION_CREATED: "Pregunta creada",
  QUESTION_DISPOSITION_REVOKED: "Disposición revocada",
  QUESTION_METADATA_CHANGED: "Datos de la pregunta cambiados",
  QUESTION_MOVED: "Pregunta movida",
  QUESTION_NOT_APPLICABLE: "Pregunta marcada «no aplica»",
  QUESTION_PUBLISHED: "Pregunta publicada",
  QUESTION_REOPENED: "Pregunta reabierta",
  QUESTIONNAIRE_BATCH_APPLIED: "Lote aplicado al cuestionario",
  QUESTIONS_REORDERED: "Preguntas reordenadas",
  RESPONSE_DRAFTED: "Borrador guardado",
  RESPONSE_SUBMITTED: "Respuesta enviada",
  RESPONSE_VALIDATED: "Respuesta validada",
  SECTION_CREATED: "Tema creado",
  SECTION_UPDATED: "Tema actualizado",
  SECTIONS_REORDERED: "Temas reordenados",
  USER_CREATED: "Usuario creado",
  VALIDATION_INVALIDATED: "Validación invalidada",
};
export const auditObjects: Record<string, string> = {
  Area: "Área",
  Evidence: "Evidencia",
  ImportBatch: "Importación",
  Project: "Proyecto",
  ProjectMember: "Miembro del proyecto",
  Question: "Pregunta",
  QuestionAssignment: "Asignación",
  QuestionDisposition: "Disposición",
  Response: "Respuesta",
  ResponseInvitation: "Invitación",
  Section: "Tema",
  Session: "Sesión",
  User: "Usuario",
  Validation: "Validación",
};
